ALTER TABLE organizations
ADD COLUMN contact_email VARCHAR(255),
ADD COLUMN visibility ENUM('PUBLIC', 'UNLISTED', 'PRIVATE') DEFAULT 'PUBLIC',
ADD COLUMN preferred_language ENUM('ENGLISH', 'HINDI', 'TAMIL', 'TELUGU', 'KANNADA', 'BENGALI') DEFAULT 'ENGLISH';
