import React from 'react';
import { X, Download, Share2 } from 'lucide-react';

export function GraphicPreviewModal({ isOpen, onClose, graphicUrl, type }) {
  if (!isOpen) return null;

  const handleDownload = () => {
    const link = document.createElement('a');
    link.href = graphicUrl;
    link.download = `${type}-graphic.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: `Tournament ${type} Graphic`,
          text: 'Check out this tournament graphic generated by GameVerse!',
          url: graphicUrl,
        });
      } catch (err) {
        console.error('Error sharing:', err);
      }
    } else {
      navigator.clipboard.writeText(graphicUrl);
      alert('Link copied to clipboard!');
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6">
      <div className="absolute inset-0 bg-slate-950/80 backdrop-blur-sm" onClick={onClose}></div>
      <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-4xl relative z-10 flex flex-col shadow-2xl overflow-hidden max-h-[90vh]">
        
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-slate-800 bg-slate-900/50">
          <div>
            <h3 className="text-xl font-bold text-white capitalize">{type.replace('-', ' ')} Graphic Preview</h3>
            <p className="text-sm text-slate-400">Preview your generated graphic before sharing</p>
          </div>
          <button 
            onClick={onClose}
            className="p-2 hover:bg-slate-800 rounded-lg text-slate-400 hover:text-white transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content - Image Preview */}
        <div className="flex-1 overflow-y-auto p-6 bg-slate-950 flex items-center justify-center min-h-[400px]">
          {graphicUrl ? (
            <img 
              src={graphicUrl} 
              alt="Generated Graphic" 
              className="max-w-full max-h-full rounded-lg shadow-xl ring-1 ring-white/10 object-contain"
            />
          ) : (
            <div className="flex flex-col items-center text-slate-500">
              <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-blue-500 mb-4"></div>
              <p>Generating high-quality graphic via SSR Engine...</p>
            </div>
          )}
        </div>

        {/* Footer Actions */}
        <div className="p-4 border-t border-slate-800 bg-slate-900/50 flex flex-wrap items-center justify-between gap-4">
          <p className="text-sm text-slate-500">
            Link expires in 90 days. Accessible via <span className="text-blue-400">CDN Storage</span>.
          </p>
          <div className="flex items-center gap-3">
            <button 
              onClick={handleShare}
              disabled={!graphicUrl}
              className="px-5 py-2.5 bg-slate-800 hover:bg-slate-700 disabled:opacity-50 text-white font-medium rounded-xl transition-colors flex items-center gap-2"
            >
              <Share2 className="w-4 h-4" /> Share API
            </button>
            <button 
              onClick={handleDownload}
              disabled={!graphicUrl}
              className="px-5 py-2.5 bg-blue-600 hover:bg-blue-500 disabled:opacity-50 text-white font-semibold rounded-xl transition-colors shadow-[0_0_15px_rgba(37,99,235,0.2)] flex items-center gap-2"
            >
              <Download className="w-4 h-4" /> Download PNG
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
