ALTER TABLE tournaments
ADD COLUMN primary_color VARCHAR(10) DEFAULT NULL,
ADD COLUMN secondary_color VARCHAR(10) DEFAULT NULL,
ADD COLUMN accent_color VARCHAR(10) DEFAULT NULL,
ADD COLUMN primary_font VARCHAR(100) DEFAULT NULL,
ADD COLUMN secondary_font VARCHAR(100) DEFAULT NULL,
ADD COLUMN brand_tagline VARCHAR(60) DEFAULT NULL,
ADD COLUMN secondary_logo_url VARCHAR(500) DEFAULT NULL;
